### ISSUE TITLE
Create PIP Account for the UAG Data Analysis Group

### ISSUE THREAD

**Issue by axelgafu** [axelgafu/mosynapi#24]
We as data analysis laboratory need to be able to publish the data analysis tools created by us. In order to do that we need to create an account in PyPI site so we can install our package with the pip command.

Use the following web page for more instructions on what to do: 
- How to submit a package to PyPI: http://peterdowns.com/posts/first-time-with-pypi.html

**Do not upload package**, create user accounts only: PyPI Live and PyPI Test.

**Comment by ArtTorres** [comment]
Account created.
