### ISSUE TITLE
Publish API Version 1.0 "Genesis" in PyPI

### ISSUE THREAD

**Issue by axelgafu** [axelgafu/mosynapi#25]
We as data analysis laboratory need to be able to publish the data analysis tools created by us. In order to do that we need to publish our API package in the PyPI site so we can install our package with the pip command.

Use the following web page for more instructions on what to do:
- How to submit a package to PyPI: http://peterdowns.com/posts/first-time-with-pypi.html

Issue #24 was to create the user accounts only. This issue is for the actual code upload.

**Comment by ArtTorres** [comment]
Pypi account and release process defined.
