### ISSUE TITLE
Define API Package License.

### ISSUE THREAD

**Issue by axelgafu** [axelgafu/mosynapi#27]
We as data analysis tool provider need to define the license type our software will be published with. An alternative is the MIT license: http://opensource.org/licenses/MIT

However, it is necessary to clarify what license the UAG needs.
Outcome of this task is a **License.txt** file which contains the actual license that will be used.

**Comment by axelgafu** [comment]
---------- Mensaje enviado ----------

De: Arturo Asael Torres Alvarez art.torres.alv@gmail.com
Fecha: 17 de noviembre de 2015, 5:30 p. m.
Asunto: Fwd: Licencia!!
Para: Axel García axel.gafu@gmail.com, Rogelio Davila Rdav90@gmail.com

Axel, 

Me puedes ayudar a hacer la modificación del archivo licence,txt?

Saludos desde "Que chua es puebla"

---------- Mensaje reenviado ----------

De: Rogelio Davila rdav90@gmail.com
Fecha: 17 de noviembre de 2015, 14:14
Asunto: Licencia!!
Para: Arturo Asael Torres Alvarez art.torres.alv@gmail.com

Estimado Asael,

Agrega esto al software:

Esta obra está licenciada bajo la Licencia Creative Commons Atribución-NoComercial-CompartirIgual 4.0 Internacional. Para ver una copia de esta licencia, visita http://creativecommons.org/licenses/by-nc-sa/4.0/.

Saludos,

Rogelio

## 

Dr. Rogelio Davila Perez
Profesor-Investigador
División de Posgrados
Universidad Autónoma de Guadalajara
Web Page: http://www.rogeliodavila.com/

**Comment by axelgafu** [comment]
License file used in the package copied from: http://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.txt

**Comment by axelgafu** [comment]
Waiting Arturo's feedback. @ArtTorres

**Comment by ArtTorres** [comment]
Task completed.
