### ISSUE TITLE
Python 2.x vs 3.x incompatibility: print call is different. 

### ISSUE THREAD

**Issue by axelgafu** [axelgafu/mosynapi#30]
TravisCI automated tests found an issue with the calls to "print" function in Python 3.x:

``` python
The command "python parseStringSample.py" exited with 1.
0.04s$ python parseFileSample.py
  File "parseFileSample.py", line 17
    print "Processing: Poema20.txt."
                                   ^
SyntaxError: invalid syntax
```

In python 3.x print calls need a parenthesis now, according with the following document:
https://docs.python.org/3/whatsnew/3.0.html

``` python
Old: print "The answer is", 2*2
New: print("The answer is", 2*2)
```

This issue has been opened to address that.

**Comment by ArtTorres** [comment]
Compatibility fixed.
